### PR TITLE
deps: Refresh dependencies

### PR DESCRIPTION
**Pull request by njhill**
grpc, netty, netty-tcnative, protobuf, gson, guava

### CODE REVIEW

**Comment by sgnk** [comment]
Do you have a plan to update dependencies and create a new release? Some of deps are out-dated and have vulnerabilities.

**Comment by njhill** [comment]
@sgnk yes, I will aim to do this soon.

**Comment by njhill** [comment]
It looks like grpc-java 1.44.x will be released very soon. Planning to wait for that and then will get this PR in and cut a new release right away.

**Comment by njhill** [comment]
@sgnk etcd-java 0.0.19 [has now been released](https://github.com/IBM/etcd-java/releases/tag/v0.0.19) with latest fixes and dependency updates.

**Comment by sgnk** [comment]
@njhill Thanks a lot!

**Pull request merged**
